services:
  spark:
    version: 2.2.0
  hdfs:
    version: 2.7.3

provider: ec2

providers:
  ec2:
    key-name: bigkp   #for west-2 
    identity-file: /home/big/keys/bigkp.pem
    instance-type: t2.micro
    region: eu-west-2
    ami: ami-01419b804382064e4   # Amazon Linux, eu-west-2
    user: ec2-user
    tenancy: default  # default | dedicated
    ebs-optimized: no  # yes | no
    instance-initiated-shutdown-behavior: terminate  # terminate | stop

launch:
  num-slaves: 2
  install-hdfs: False
